theme = "bento"
languageCode = "en-us"
baseurl = "https://www.example.com/"
title = "upHill"

author = "Leonardo Faria"
copyright = "MIT"

[taxonomies]
category = "categories"
tag = "tags"

# Better code higlighting
# via https://discourse.gohugo.io/t/pygmentscodefences-how-to-choose-themes/3842/3
pygmentsCodefences = true
pygmentsStyle = "vs"

# Integrations
googleAnalytics = "UA-XXXXXX-YY"
disqusShortname = "bento-hugo-theme"

# Hightlight theme
[markup.highlight]
  style = "github"

# Allow HTML rendering inside markdown
[markup.goldmark.renderer]
  unsafe = true

[params]
  # Show intro in the home page (with headline and description) file intro.html
  intro = true
  headline = "This is a headline cambiami in config.toml"
  description = "A minimalist theme for Hugo, build with Tailwind CSS."

  # Copyright note in the footer
  copyright = "Copyright © 2020 Italo"

  # Image in the homepage. You can setup a different image for social media
  # cover = "images/vancouver.jpg" (originale)
  cover = "images/granParadiso.jpg"

  ogImage = "images/og_image.jpg"

  # Social media usernames
  #github = "XXXX"
  #twitter = "XXXX"
  instagram = "X"
  linkedin = "https://linkedin.com/in/XXXX"
  email = "email@xxxx.com"

  # Learn more about webmention
  # https://sebastiandedeyne.com/adding-webmentions-to-my-blog/
  # webmention = ""
  # productionBaseUrl is need if you want to receive webmentions in local environment
  # productionBaseUrl = "https://yourwebsite.com"

  # Avatar (shown in the homepage)
  # avatar = "images/avatar.jpg"
  avatar = "images/avatar1.jpg"
  # Bio is shown in the end of posts
  authorBio = "Bento is a doggo who likes to code."

# If you want to use fathom (https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
  siteID = "XXXXX"
  # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
  serverURL = "analytics.example.com"

# If you want to use umami (https://umami.is/) for analytics, add this section
[params.umami]
  siteID = "XXXXX"
  trackerScript = "//umami.example.com/umami.js"

# Items in the top menu
[menu]

[[menu.main]]
  # name = "level-3"
  # url = "/post/level-3"
  # weight = 2

  [[menu.main]]
    name = "Racconti di viaggio"
    url = "/viaggi/ListaViaggi"
    weight = 1

    [[menu.main]]
      name = "Blog"
      url = "/blog/"
      weight = 2

  # [[menu.main]]
  #   name = "level-2-a"
  #   url = "/level-1/level-2-a/"
  #   weight = 2
  #
  #   [[menu.main]]
  #     name = "level-3"
  #     url = "/level-1/level-2-a/level-3/"
  #     weight = 2
  #
  #     [[menu.main]]
  #       name = "level-4"
  #       url = "/level-1/level-2-a/level-3/level-4/"
  #       weight = 2
  #
  #   [[menu.main]]
  #     name = "level-1-a"
  #     url = "/post/level-1-a/"
  #     weight = 3

  [[menu.main]]
      name = "About"
      url = "/about"
      weight = 98

  [[menu.main]]
      name = "Archives"
      url = "/archives"
      weight = 99

  # [[menu.main]]
  #     name = "Source code"
  #     url = "https://github.com/leonardofaria/bento"
  #     weight = 1
